#!/usr/bin/env python3
"""Generate the production script from the two source JSONs.

    python3 scripts/make_jungle_v2.py > scripts/jungle-rescue-v2-production.md

Source of truth is scripts/source/jungle-rescue-v2.json (narration) and
scripts/source/jungle-rescue-v2-sfx.json. Edit those, regenerate this.
"""
import json, os, sys
H = os.path.dirname(os.path.abspath(__file__))
N = json.load(open(os.path.join(H, "source", "jungle-rescue-v2.json"), encoding="utf-8"))
S = json.load(open(os.path.join(H, "source", "jungle-rescue-v2-sfx.json"), encoding="utf-8"))

VOICES = [
 ("Coco", "the existing Coco voice — keep it", "energetic, warm, wide range. Carries the rally and both catchphrases"),
 ("Narrator", "the existing Narrator voice — keep it", "steady, warm, never rushed"),
 ("Elephant", "NEW — big adult male, very deep", "slow, booming, completely matter-of-fact. The flatness is the joke"),
 ("Frog", "NEW — small, squeaky, comic", "high and fast, constantly interrupted by hiccups"),
 ("Giraffe", "NEW — female, high and gentle", "VERY slow, stretched vowels, sing-song. Every word a journey"),
 ("Lion", "NEW — enormous male, sleepy", "deadpan, harmless, half asleep. Never threatening"),
]
out = []
w = out.append
w("# Jungle Rescue Patrol v2 — production script\n")
w("Generated from `scripts/source/jungle-rescue-v2.json` and `…-sfx.json`.")
w("Do not edit this file — edit the JSON and regenerate.\n")
w("**%d narration clips · %d sound effects · 9 cards**\n" % (len(N), len(S)))

w("## Voices\n")
w("| character | voice | direction |")
w("|---|---|---|")
for a, b, c in VOICES:
    w("| **%s** | %s | %s |" % (a, b, c))
w("")
w("Settings: `model_id: eleven_v3`, `output_format: mp3_44100_128`. Tags in the")
w("**tone** column go at the front of the text you send. Suggested per voice —")
w("Coco `stability 0.40`, Narrator `0.50`, Elephant `0.60`, Frog `0.35`,")
w("Giraffe `0.55`, Lion `0.65`; `similarity_boost 0.8`, `style 0.35`.\n")

w("## Repeated on purpose\n")
w("These must sound **identical every time** — same pitch, same rhythm — so the")
w("children can join in. Repetition was the strongest device in either story.\n")
w("- **The rally:** `जंगल बचाओ टीम… तैयार?!` — leave a real beat of silence after it")
w("- **The mess cry:** `गंदा! गंदा! बहुत गंदा!` — used exactly three times")
w("- **Every acknowledgement:** `YES! <CARD>! शाबाश किशु मिशु!` + what changed")
w("- **Every card ask rhymes** — two beats, sing-song\n")

scene = None
for f, sc, who, direction, text, tag in N:
    if sc != scene:
        scene = sc
        w("\n---\n\n## %s\n" % sc)
        w("| file | who | tone | line | direction |")
        w("|---|---|---|---|---|")
    w("| `%s` | **%s** | `%s` | %s | %s |" % (f, who, tag, text, direction))

w("\n---\n\n## Sound effects\n")
w("Generate with ElevenLabs sound-generation. `prompt_influence 0.6`; raise")
w("toward 0.8 if a take drifts, lower toward 0.3 if it sounds stiff. Take")
w("several of each — they are cheap and variable.\n")
w("| file | scene | seconds | prompt |")
w("|---|---|---|---|")
for f, sc, prompt, secs in S:
    w("| `%s` | %s | %.1f | %s |" % (f, sc, secs, prompt))

w("\n---\n\n## Levelling — do this to every file before it goes in\n")
w("```")
w("# narration")
w('ffmpeg -i in.mp3 -af "loudnorm=I=-16:TP=-1.5:LRA=7" -c:a libmp3lame -q:a 2 out.mp3')
w("")
w("# sound effects: -20 dB mean, peaks under -1.5 dBTP")
w("ffmpeg -i in.mp3 -af volumedetect -f null -          # read mean_volume")
w('ffmpeg -i in.mp3 -af "volume=<-20 minus mean>dB,alimiter=limit=0.85:level=false" \\')
w("       -c:a libmp3lame -q:a 2 out.mp3")
w("```")
w("")
w("`alimiter` **must** carry `level=false` — without it, it auto-levels to its")
w("own ceiling and silently undoes the gain staging.\n")
w("Then listen on a phone, speaker only, from two metres. A phone speaker")
w("produces almost nothing below 450 Hz.\n")
print("\n".join(out))
